services:

    otel-collector:
        image: otel/opentelemetry-collector-contrib:0.118.0
        container_name: otel-collector
        command: ["--config=/etc/open-telemetry.yml"]
        volumes:
            - ./open-telemetry.yml:/etc/open-telemetry.yml
        ports:
            - "4317:4317"
            - "4318:4318"
            - "9464:9464"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - ecommerce

    loki:
        image: grafana/loki:3.0.0
        container_name: loki
        volumes:
            - loki-data:/loki
        ports:
            - "3100:3100"
        networks:
            - ecommerce

    tempo:
        image: grafana/tempo:2.7.2
        container_name: tempo
        command:
            - "-config.file=/etc/tempo.yml"
        volumes:
            - ./tempo-config.yml:/etc/tempo.yml
            - tempo-data:/var/tempo
        ports:
            - "3200:3200"
        networks:
            - ecommerce

    prometheus:
        image: prom/prometheus:v2.53.1
        container_name: prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.enable-lifecycle"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus-data:/prometheus
        ports:
            - "9090:9090"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - ecommerce

    grafana:
        image: grafana/grafana:11.4.0
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP="false"
            - GF_SERVER_HTTP_PORT=3000
        volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        ports:
            - "3000:3000"
        depends_on:
            - prometheus
            - tempo
            - loki
        networks:
            - ecommerce

    postgresql:
        image: postgres:16-alpine
        container_name: postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ecommerce
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - ecommerce

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        container_name: kafka
        ports:
            - "9092:9092"
            - "9094:9094"
        volumes:
            - kafka-data:/var/lib/kafka/data
        networks:
            - ecommerce
        environment:
            - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
            - KAFKA_NODE_ID=1
            - KAFKA_PROCESS_ROLES=broker,controller
            - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
            - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
            - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
            - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
            - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false

    kafka-ui:
        image: docker.redpanda.com/redpandadata/console:latest
        container_name: redpanda-console
        depends_on:
            - kafka
        ports:
            - "9091:8080"
        networks:
            - ecommerce
        environment:
            - KAFKA_BROKERS=kafka:9092

    order-service:
        profiles:
            - services
        build:
            context: ./service-order
            dockerfile: Dockerfile
        image: order-service:latest
        container_name: order-service
        ports:
            - "8081:8081"
        networks:
            - ecommerce
        depends_on:
            otel-collector:
                condition: service_started
            postgresql:
                condition: service_healthy
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - OTEL_SERVICE_NAME=order-service
            - OTEL_TRACES_EXPORTER=otlp
            - OTEL_METRICS_EXPORTER=otlp
            - OTEL_LOGS_EXPORTER=otlp
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
            - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
            - OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED="true"

    catalog-service:
        profiles:
            - services
        build:
            context: ./service-catalog
            dockerfile: Dockerfile
        image: catalog-service:latest
        container_name: catalog-service
        ports:
            - "8082:8082"
        networks:
            - ecommerce
        depends_on:
            otel-collector:
                condition: service_started
            postgresql:
                condition: service_healthy
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - OTEL_SERVICE_NAME=catalog-service
            - OTEL_TRACES_EXPORTER=otlp
            - OTEL_METRICS_EXPORTER=otlp
            - OTEL_LOGS_EXPORTER=otlp
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
            - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
            - OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED="true"

    billing-service:
        profiles:
            - services
        build:
            context: ./service-billing
            dockerfile: Dockerfile
        image: billing-service:latest
        container_name: billing-service
        ports:
            - "8083:8083"
        networks:
            - ecommerce
        depends_on:
            otel-collector:
                condition: service_started
            postgresql:
                condition: service_healthy
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - OTEL_SERVICE_NAME=billing-service
            - OTEL_TRACES_EXPORTER=otlp
            - OTEL_METRICS_EXPORTER=otlp
            - OTEL_LOGS_EXPORTER=otlp
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
            - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
            - OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED="true"

networks:
    ecommerce:
        name: ecommerce
        driver: bridge

volumes:
    grafana-data:
    prometheus-data:
    loki-data:
    tempo-data:
    postgresql-data:
    kafka-data:
