spring:
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
          enabled: true
